'use strict';

// Curated emoji dataset — 9 categories matching Chrome / Edge / Slack.
// Each item: [glyph, name, keywords] — name and keywords power the search.
// Trimmed-but-broad coverage so the picker stays under ~1k entries and feels
// fast without bundling full Unicode CLDR annotations.

window.PRIVOO_EMOJI_DATA = {
  categories: [
    { id: 'recent',   label: 'Recent',         icon: '🕒' },
    { id: 'smileys',  label: 'Smileys & people', icon: '😀' },
    { id: 'nature',   label: 'Animals & nature', icon: '🐶' },
    { id: 'food',     label: 'Food & drink',   icon: '🍎' },
    { id: 'activity', label: 'Activities',     icon: '⚽' },
    { id: 'travel',   label: 'Travel & places',icon: '✈️' },
    { id: 'objects',  label: 'Objects',        icon: '💡' },
    { id: 'symbols',  label: 'Symbols',        icon: '❤️' },
    { id: 'flags',    label: 'Flags',          icon: '🏳️' },
  ],
  emojis: {
    smileys: [
      ['😀','grinning face','smile happy'],
      ['😃','grinning face with big eyes','smile happy joy'],
      ['😄','grinning face with smiling eyes','happy smile joy'],
      ['😁','beaming face with smiling eyes','grin happy'],
      ['😆','grinning squinting face','laugh haha'],
      ['😅','grinning face with sweat','laugh nervous'],
      ['🤣','rolling on the floor laughing','rofl laugh hilarious'],
      ['😂','face with tears of joy','laugh crying funny'],
      ['🙂','slightly smiling face','smile'],
      ['🙃','upside-down face','silly sarcastic'],
      ['😉','winking face','wink flirt'],
      ['😊','smiling face with smiling eyes','blush happy'],
      ['😇','smiling face with halo','angel innocent'],
      ['🥰','smiling face with hearts','love adore'],
      ['😍','smiling face with heart-eyes','love crush'],
      ['🤩','star-struck','amazed wow'],
      ['😘','face blowing a kiss','kiss flirt'],
      ['😗','kissing face','kiss'],
      ['😚','kissing face with closed eyes','kiss'],
      ['😙','kissing face with smiling eyes','kiss'],
      ['🥲','smiling face with tear','grateful happy cry'],
      ['😋','face savoring food','yum delicious'],
      ['😛','face with tongue','tongue silly'],
      ['😜','winking face with tongue','silly playful'],
      ['🤪','zany face','crazy goofy'],
      ['😝','squinting face with tongue','silly playful'],
      ['🤑','money-mouth face','money rich'],
      ['🤗','hugging face','hug embrace'],
      ['🤭','face with hand over mouth','oops shy'],
      ['🤫','shushing face','quiet secret'],
      ['🤔','thinking face','think hmm'],
      ['🤐','zipper-mouth face','quiet secret'],
      ['🤨','face with raised eyebrow','skeptical suspicious'],
      ['😐','neutral face','blank meh'],
      ['😑','expressionless face','blank meh'],
      ['😶','face without mouth','speechless'],
      ['😏','smirking face','smirk sly'],
      ['😒','unamused face','meh annoyed'],
      ['🙄','face with rolling eyes','annoyed whatever'],
      ['😬','grimacing face','awkward yikes'],
      ['🤥','lying face','liar pinocchio'],
      ['😌','relieved face','calm peaceful'],
      ['😔','pensive face','sad thoughtful'],
      ['😪','sleepy face','tired sleep'],
      ['🤤','drooling face','desire'],
      ['😴','sleeping face','sleep zzz'],
      ['😷','face with medical mask','sick mask'],
      ['🤒','face with thermometer','sick fever'],
      ['🤕','face with head-bandage','hurt injured'],
      ['🤢','nauseated face','sick gross'],
      ['🤮','face vomiting','sick gross'],
      ['🤧','sneezing face','sneeze sick'],
      ['🥵','hot face','hot sweat'],
      ['🥶','cold face','cold freeze'],
      ['🥴','woozy face','drunk dizzy'],
      ['😵','knocked-out face','dizzy dead'],
      ['🤯','exploding head','mind-blown wow'],
      ['🤠','cowboy hat face','cowboy western'],
      ['🥳','partying face','party celebration'],
      ['🥸','disguised face','glasses incognito'],
      ['😎','smiling face with sunglasses','cool sunglasses'],
      ['🤓','nerd face','nerd glasses'],
      ['🧐','face with monocle','curious posh'],
      ['😕','confused face','unsure puzzled'],
      ['😟','worried face','worry anxious'],
      ['🙁','slightly frowning face','sad frown'],
      ['☹️','frowning face','sad frown'],
      ['😮','face with open mouth','wow surprised'],
      ['😯','hushed face','surprised'],
      ['😲','astonished face','shocked wow'],
      ['😳','flushed face','embarrassed blush'],
      ['🥺','pleading face','beg puppy eyes'],
      ['😦','frowning face with open mouth','shocked'],
      ['😧','anguished face','shock'],
      ['😨','fearful face','scared afraid'],
      ['😰','anxious face with sweat','nervous sweat'],
      ['😥','sad but relieved face','disappointed relief'],
      ['😢','crying face','cry sad tear'],
      ['😭','loudly crying face','sob bawl cry'],
      ['😱','face screaming in fear','scream shock'],
      ['😖','confounded face','frustrated'],
      ['😣','persevering face','struggling'],
      ['😞','disappointed face','sad let down'],
      ['😓','downcast face with sweat','sweat tired'],
      ['😩','weary face','exhausted'],
      ['😫','tired face','exhausted'],
      ['🥱','yawning face','tired bored'],
      ['😤','face with steam from nose','frustrated angry'],
      ['😡','enraged face','angry mad red'],
      ['😠','angry face','mad'],
      ['🤬','face with symbols on mouth','swear curse'],
      ['😈','smiling face with horns','devil mischief'],
      ['👿','angry face with horns','devil mad'],
      ['💀','skull','dead'],
      ['☠️','skull and crossbones','death poison'],
      ['💩','pile of poo','poo crap'],
      ['🤡','clown face','clown silly'],
      ['👹','ogre','monster'],
      ['👺','goblin','monster'],
      ['👻','ghost','spooky halloween'],
      ['👽','alien','space ufo'],
      ['👾','alien monster','space invader game'],
      ['🤖','robot','bot'],
      ['😺','grinning cat','cat happy'],
      ['😸','grinning cat with smiling eyes','cat happy'],
      ['😹','cat with tears of joy','cat laugh'],
      ['😻','smiling cat with heart-eyes','cat love'],
      ['😼','cat with wry smile','cat smug'],
      ['😽','kissing cat','cat kiss'],
      ['🙀','weary cat','cat shock'],
      ['😿','crying cat','cat sad'],
      ['😾','pouting cat','cat angry'],
      ['❤️','red heart','love heart'],
      ['🧡','orange heart','love heart'],
      ['💛','yellow heart','love heart'],
      ['💚','green heart','love heart'],
      ['💙','blue heart','love heart'],
      ['💜','purple heart','love heart'],
      ['🖤','black heart','love'],
      ['🤍','white heart','love'],
      ['🤎','brown heart','love'],
      ['💔','broken heart','heartbreak sad'],
      ['❣️','heart exclamation','love'],
      ['💕','two hearts','love'],
      ['💞','revolving hearts','love'],
      ['💓','beating heart','love'],
      ['💗','growing heart','love'],
      ['💖','sparkling heart','love'],
      ['💘','heart with arrow','cupid love'],
      ['💝','heart with ribbon','love gift'],
      ['💟','heart decoration','love'],
      ['💌','love letter','letter'],
      ['💋','kiss mark','lips kiss'],
      ['👋','waving hand','wave hi bye'],
      ['🤚','raised back of hand','stop'],
      ['🖐️','hand with fingers splayed','five hand'],
      ['✋','raised hand','stop high-five'],
      ['🖖','vulcan salute','spock'],
      ['👌','OK hand','ok perfect'],
      ['🤌','pinched fingers','italian gesture'],
      ['🤏','pinching hand','small tiny'],
      ['✌️','victory hand','peace'],
      ['🤞','crossed fingers','luck hope'],
      ['🤟','love-you gesture','ily'],
      ['🤘','sign of the horns','rock metal'],
      ['🤙','call me hand','call shaka'],
      ['👈','backhand index pointing left','left arrow'],
      ['👉','backhand index pointing right','right arrow'],
      ['👆','backhand index pointing up','up'],
      ['👇','backhand index pointing down','down'],
      ['☝️','index pointing up','one point'],
      ['👍','thumbs up','like yes good'],
      ['👎','thumbs down','dislike no bad'],
      ['👊','oncoming fist','punch fist bump'],
      ['✊','raised fist','power solidarity'],
      ['🤛','left-facing fist','fist bump'],
      ['🤜','right-facing fist','fist bump'],
      ['👏','clapping hands','clap applause'],
      ['🙌','raising hands','praise hooray'],
      ['👐','open hands','hug'],
      ['🤲','palms up together','prayer dua'],
      ['🤝','handshake','deal agreement'],
      ['🙏','folded hands','please thanks prayer'],
      ['💅','nail polish','nails'],
      ['🤳','selfie','phone'],
      ['💪','flexed biceps','strong muscle'],
      ['🦾','mechanical arm','robot strong'],
      ['🦿','mechanical leg','robot'],
      ['🦵','leg','foot'],
      ['🦶','foot','feet'],
      ['👂','ear','listen'],
      ['🦻','ear with hearing aid','accessibility'],
      ['👃','nose','smell'],
      ['🧠','brain','smart mind'],
      ['🫀','anatomical heart','heart organ'],
      ['🫁','lungs','breath'],
      ['🦷','tooth','dentist'],
      ['🦴','bone','skeleton'],
      ['👀','eyes','look see'],
      ['👁️','eye','watch'],
      ['👅','tongue','taste'],
      ['👄','mouth','lips'],
      ['👶','baby','infant'],
      ['🧒','child','kid'],
      ['👦','boy','child'],
      ['👧','girl','child'],
      ['🧑','person','adult'],
      ['👨','man','male'],
      ['👩','woman','female'],
      ['🧓','older person','elderly'],
      ['👴','old man','grandfather'],
      ['👵','old woman','grandmother'],
    ],
    nature: [
      ['🐶','dog face','puppy pet'],
      ['🐱','cat face','kitten pet'],
      ['🐭','mouse face','rodent'],
      ['🐹','hamster','pet'],
      ['🐰','rabbit face','bunny'],
      ['🦊','fox','animal'],
      ['🐻','bear','animal'],
      ['🐼','panda','animal'],
      ['🐨','koala','australia'],
      ['🐯','tiger face','animal'],
      ['🦁','lion','animal king'],
      ['🐮','cow face','animal moo'],
      ['🐷','pig face','animal oink'],
      ['🐽','pig nose','animal'],
      ['🐸','frog','animal ribbit'],
      ['🐵','monkey face','animal ape'],
      ['🙈','see-no-evil monkey','monkey'],
      ['🙉','hear-no-evil monkey','monkey'],
      ['🙊','speak-no-evil monkey','monkey'],
      ['🐒','monkey','animal'],
      ['🐔','chicken','bird'],
      ['🐧','penguin','bird arctic'],
      ['🐦','bird','flying'],
      ['🐤','baby chick','bird'],
      ['🐣','hatching chick','bird egg'],
      ['🐥','front-facing baby chick','bird'],
      ['🦆','duck','bird'],
      ['🦅','eagle','bird'],
      ['🦉','owl','bird night'],
      ['🦇','bat','animal halloween'],
      ['🐺','wolf','animal'],
      ['🐗','boar','animal pig'],
      ['🐴','horse face','animal'],
      ['🦄','unicorn','fantasy'],
      ['🐝','honeybee','insect'],
      ['🪱','worm','insect'],
      ['🐛','bug','insect caterpillar'],
      ['🦋','butterfly','insect'],
      ['🐌','snail','slow'],
      ['🐞','lady beetle','insect ladybug'],
      ['🐜','ant','insect'],
      ['🪰','fly','insect'],
      ['🪲','beetle','insect'],
      ['🦗','cricket','insect'],
      ['🕷️','spider','insect halloween'],
      ['🦂','scorpion','insect'],
      ['🐢','turtle','reptile slow'],
      ['🐍','snake','reptile'],
      ['🦎','lizard','reptile'],
      ['🦖','t-rex','dinosaur'],
      ['🦕','sauropod','dinosaur'],
      ['🐙','octopus','sea'],
      ['🦑','squid','sea'],
      ['🦐','shrimp','sea food'],
      ['🦞','lobster','sea food'],
      ['🦀','crab','sea'],
      ['🐡','blowfish','sea'],
      ['🐠','tropical fish','sea'],
      ['🐟','fish','sea'],
      ['🐬','dolphin','sea'],
      ['🐳','spouting whale','sea'],
      ['🐋','whale','sea'],
      ['🦈','shark','sea'],
      ['🐊','crocodile','reptile'],
      ['🐅','tiger','animal'],
      ['🐆','leopard','animal'],
      ['🦓','zebra','animal'],
      ['🦍','gorilla','animal ape'],
      ['🦧','orangutan','animal ape'],
      ['🐘','elephant','animal'],
      ['🦛','hippopotamus','animal'],
      ['🦏','rhinoceros','animal'],
      ['🐪','camel','desert'],
      ['🐫','two-hump camel','desert'],
      ['🦒','giraffe','animal tall'],
      ['🦘','kangaroo','animal australia'],
      ['🐃','water buffalo','animal'],
      ['🐂','ox','animal'],
      ['🐄','cow','animal'],
      ['🐎','horse','animal'],
      ['🐖','pig','animal'],
      ['🐏','ram','animal'],
      ['🐑','ewe','animal sheep'],
      ['🦙','llama','animal'],
      ['🐐','goat','animal'],
      ['🦌','deer','animal'],
      ['🐕','dog','animal pet'],
      ['🐩','poodle','dog pet'],
      ['🦮','guide dog','accessibility'],
      ['🐈','cat','animal pet'],
      ['🐓','rooster','bird farm'],
      ['🦃','turkey','bird thanksgiving'],
      ['🦚','peacock','bird'],
      ['🦜','parrot','bird'],
      ['🦢','swan','bird'],
      ['🦩','flamingo','bird pink'],
      ['🕊️','dove','bird peace'],
      ['🐇','rabbit','animal'],
      ['🦝','raccoon','animal'],
      ['🦨','skunk','animal'],
      ['🦡','badger','animal'],
      ['🦦','otter','animal'],
      ['🦥','sloth','animal slow'],
      ['🐁','mouse','animal'],
      ['🐀','rat','animal'],
      ['🐿️','chipmunk','animal squirrel'],
      ['🦔','hedgehog','animal'],
      ['🐾','paw prints','animal'],
      ['🌵','cactus','plant desert'],
      ['🎄','christmas tree','holiday'],
      ['🌲','evergreen tree','plant'],
      ['🌳','deciduous tree','plant'],
      ['🌴','palm tree','beach'],
      ['🌱','seedling','plant grow'],
      ['🌿','herb','plant'],
      ['☘️','shamrock','plant luck'],
      ['🍀','four leaf clover','luck'],
      ['🎍','pine decoration','japan'],
      ['🎋','tanabata tree','japan'],
      ['🍃','leaf fluttering in wind','plant'],
      ['🍂','fallen leaf','autumn'],
      ['🍁','maple leaf','autumn canada'],
      ['🌾','sheaf of rice','plant'],
      ['🌺','hibiscus','flower'],
      ['🌻','sunflower','flower'],
      ['🌹','rose','flower love'],
      ['🥀','wilted flower','flower sad'],
      ['🌷','tulip','flower'],
      ['🌼','blossom','flower'],
      ['🌸','cherry blossom','flower sakura'],
      ['💐','bouquet','flowers gift'],
      ['🍄','mushroom','fungus'],
      ['🌰','chestnut','nut'],
      ['🐚','spiral shell','sea beach'],
      ['🪨','rock','stone'],
      ['🪵','wood','log'],
      ['🌍','globe showing europe-africa','earth world'],
      ['🌎','globe showing americas','earth world'],
      ['🌏','globe showing asia-australia','earth world'],
      ['🌑','new moon','dark'],
      ['🌒','waxing crescent moon','moon'],
      ['🌓','first quarter moon','moon'],
      ['🌔','waxing gibbous moon','moon'],
      ['🌕','full moon','moon'],
      ['🌖','waning gibbous moon','moon'],
      ['🌗','last quarter moon','moon'],
      ['🌘','waning crescent moon','moon'],
      ['🌙','crescent moon','night'],
      ['🌚','new moon face','moon'],
      ['🌛','first quarter moon face','moon'],
      ['🌜','last quarter moon face','moon'],
      ['🌡️','thermometer','temperature'],
      ['☀️','sun','sunny weather'],
      ['🌝','full moon face','moon'],
      ['🌞','sun with face','sunny'],
      ['🪐','ringed planet','space saturn'],
      ['⭐','star','star'],
      ['🌟','glowing star','star'],
      ['🌠','shooting star','star wish'],
      ['🌌','milky way','space galaxy'],
      ['☁️','cloud','weather'],
      ['⛅','sun behind cloud','weather'],
      ['⛈️','cloud with lightning and rain','storm'],
      ['🌤️','sun behind small cloud','weather'],
      ['🌥️','sun behind large cloud','weather'],
      ['🌦️','sun behind rain cloud','weather'],
      ['🌧️','cloud with rain','weather'],
      ['🌨️','cloud with snow','weather'],
      ['🌩️','cloud with lightning','weather'],
      ['🌪️','tornado','weather'],
      ['🌫️','fog','weather'],
      ['🌬️','wind face','weather'],
      ['🌀','cyclone','spiral'],
      ['🌈','rainbow','pride'],
      ['🌂','closed umbrella','rain'],
      ['☂️','umbrella','rain'],
      ['☔','umbrella with rain drops','rain'],
      ['⛱️','umbrella on ground','beach'],
      ['⚡','high voltage','lightning'],
      ['❄️','snowflake','snow cold'],
      ['☃️','snowman','snow winter'],
      ['⛄','snowman without snow','snow'],
      ['☄️','comet','space'],
      ['🔥','fire','flame hot lit'],
      ['💧','droplet','water'],
      ['🌊','water wave','sea ocean'],
    ],
    food: [
      ['🍏','green apple','fruit'],
      ['🍎','red apple','fruit'],
      ['🍐','pear','fruit'],
      ['🍊','tangerine','orange fruit'],
      ['🍋','lemon','fruit'],
      ['🍌','banana','fruit'],
      ['🍉','watermelon','fruit'],
      ['🍇','grapes','fruit wine'],
      ['🍓','strawberry','fruit'],
      ['🫐','blueberries','fruit'],
      ['🍈','melon','fruit'],
      ['🍒','cherries','fruit'],
      ['🍑','peach','fruit'],
      ['🥭','mango','fruit'],
      ['🍍','pineapple','fruit'],
      ['🥥','coconut','fruit'],
      ['🥝','kiwi fruit','fruit'],
      ['🍅','tomato','fruit'],
      ['🍆','eggplant','vegetable'],
      ['🥑','avocado','fruit'],
      ['🥦','broccoli','vegetable'],
      ['🥬','leafy green','vegetable'],
      ['🥒','cucumber','vegetable'],
      ['🌶️','hot pepper','spicy'],
      ['🫑','bell pepper','vegetable'],
      ['🌽','ear of corn','vegetable'],
      ['🥕','carrot','vegetable'],
      ['🫒','olive','food'],
      ['🧄','garlic','food'],
      ['🧅','onion','food'],
      ['🥔','potato','vegetable'],
      ['🍠','roasted sweet potato','food'],
      ['🥐','croissant','pastry bread'],
      ['🥯','bagel','bread'],
      ['🍞','bread','toast'],
      ['🥖','baguette','french bread'],
      ['🫓','flatbread','bread'],
      ['🥨','pretzel','snack'],
      ['🧀','cheese wedge','dairy'],
      ['🥚','egg','breakfast'],
      ['🍳','cooking','egg breakfast'],
      ['🧈','butter','dairy'],
      ['🥞','pancakes','breakfast'],
      ['🧇','waffle','breakfast'],
      ['🥓','bacon','meat breakfast'],
      ['🥩','cut of meat','steak'],
      ['🍗','poultry leg','chicken drumstick'],
      ['🍖','meat on bone','food'],
      ['🌭','hot dog','food'],
      ['🍔','hamburger','burger food'],
      ['🍟','french fries','food chips'],
      ['🍕','pizza','food slice'],
      ['🥪','sandwich','food lunch'],
      ['🥙','stuffed flatbread','food'],
      ['🧆','falafel','food'],
      ['🌮','taco','food mexican'],
      ['🌯','burrito','food mexican'],
      ['🫔','tamale','food mexican'],
      ['🥗','green salad','food healthy'],
      ['🥘','shallow pan of food','paella'],
      ['🫕','fondue','food'],
      ['🥫','canned food','food'],
      ['🍝','spaghetti','pasta food'],
      ['🍜','steaming bowl','noodles ramen'],
      ['🍲','pot of food','stew food'],
      ['🍛','curry rice','food'],
      ['🍣','sushi','food japanese'],
      ['🍱','bento box','food japanese'],
      ['🥟','dumpling','food'],
      ['🦪','oyster','food'],
      ['🍤','fried shrimp','tempura food'],
      ['🍙','rice ball','onigiri'],
      ['🍚','cooked rice','food'],
      ['🍘','rice cracker','food'],
      ['🍥','fish cake with swirl','food'],
      ['🥠','fortune cookie','food'],
      ['🥮','moon cake','food'],
      ['🍢','oden','food'],
      ['🍡','dango','food'],
      ['🍧','shaved ice','dessert'],
      ['🍨','ice cream','dessert'],
      ['🍦','soft ice cream','dessert'],
      ['🥧','pie','dessert'],
      ['🧁','cupcake','dessert'],
      ['🍰','shortcake','cake dessert'],
      ['🎂','birthday cake','cake party'],
      ['🍮','custard','flan dessert'],
      ['🍭','lollipop','candy'],
      ['🍬','candy','sweet'],
      ['🍫','chocolate bar','candy'],
      ['🍿','popcorn','snack movies'],
      ['🍩','doughnut','dessert'],
      ['🍪','cookie','dessert'],
      ['🌰','chestnut','nut'],
      ['🥜','peanuts','nut'],
      ['🍯','honey pot','sweet'],
      ['🥛','glass of milk','drink dairy'],
      ['🍼','baby bottle','baby drink'],
      ['☕','hot beverage','coffee tea'],
      ['🫖','teapot','drink tea'],
      ['🍵','teacup without handle','tea matcha'],
      ['🧃','beverage box','juice drink'],
      ['🥤','cup with straw','drink soda'],
      ['🧋','bubble tea','drink boba'],
      ['🍶','sake','drink japanese'],
      ['🍺','beer mug','drink'],
      ['🍻','clinking beer mugs','drink cheers'],
      ['🥂','clinking glasses','drink cheers'],
      ['🍷','wine glass','drink'],
      ['🥃','tumbler glass','drink whiskey'],
      ['🍸','cocktail glass','drink martini'],
      ['🍹','tropical drink','drink'],
      ['🍾','bottle with popping cork','champagne celebrate'],
      ['🧉','mate','drink'],
      ['🧊','ice','cold'],
      ['🥢','chopsticks','food'],
      ['🍽️','fork and knife with plate','dinner food'],
      ['🍴','fork and knife','food'],
      ['🥄','spoon','food'],
      ['🔪','kitchen knife','cooking'],
      ['🏺','amphora','jar greek'],
    ],
    activity: [
      ['⚽','soccer ball','football sport'],
      ['🏀','basketball','sport'],
      ['🏈','american football','sport'],
      ['⚾','baseball','sport'],
      ['🥎','softball','sport'],
      ['🎾','tennis','sport'],
      ['🏐','volleyball','sport'],
      ['🏉','rugby football','sport'],
      ['🥏','flying disc','frisbee'],
      ['🎱','pool 8 ball','billiards'],
      ['🪀','yo-yo','toy'],
      ['🏓','ping pong','table tennis sport'],
      ['🏸','badminton','sport'],
      ['🏒','ice hockey','sport'],
      ['🏑','field hockey','sport'],
      ['🥍','lacrosse','sport'],
      ['🏏','cricket game','sport'],
      ['🪃','boomerang','toy'],
      ['🥅','goal net','sport'],
      ['⛳','flag in hole','golf'],
      ['🪁','kite','toy'],
      ['🏹','bow and arrow','archery'],
      ['🎣','fishing pole','fish'],
      ['🤿','diving mask','swim'],
      ['🥊','boxing glove','fight sport'],
      ['🥋','martial arts uniform','karate judo'],
      ['🎽','running shirt','sport'],
      ['🛹','skateboard','sport'],
      ['🛼','roller skate','sport'],
      ['🛷','sled','winter'],
      ['⛸️','ice skate','winter sport'],
      ['🥌','curling stone','winter sport'],
      ['🎿','skis','winter sport'],
      ['⛷️','skier','winter sport'],
      ['🏂','snowboarder','winter sport'],
      ['🪂','parachute','skydive'],
      ['🏋️','person lifting weights','gym fitness'],
      ['🤼','people wrestling','sport'],
      ['🤸','person cartwheeling','gymnastics'],
      ['⛹️','person bouncing ball','basketball'],
      ['🤺','person fencing','sport'],
      ['🏇','horse racing','sport'],
      ['🧘','person in lotus position','yoga meditation'],
      ['🏄','person surfing','sport surf'],
      ['🏊','person swimming','swim sport'],
      ['🤽','person playing water polo','sport'],
      ['🚣','person rowing boat','sport'],
      ['🧗','person climbing','sport'],
      ['🚵','person mountain biking','bike sport'],
      ['🚴','person biking','bike sport'],
      ['🏆','trophy','win'],
      ['🥇','1st place medal','win gold'],
      ['🥈','2nd place medal','silver'],
      ['🥉','3rd place medal','bronze'],
      ['🏅','sports medal','win'],
      ['🎖️','military medal','honor'],
      ['🏵️','rosette','badge'],
      ['🎗️','reminder ribbon','support'],
      ['🎫','ticket','admission'],
      ['🎟️','admission tickets','event'],
      ['🎪','circus tent','event'],
      ['🤹','person juggling','circus'],
      ['🎭','performing arts','theater drama'],
      ['🩰','ballet shoes','dance'],
      ['🎨','artist palette','art paint'],
      ['🎬','clapper board','film movie'],
      ['🎤','microphone','sing karaoke'],
      ['🎧','headphone','music'],
      ['🎼','musical score','music'],
      ['🎹','musical keyboard','piano music'],
      ['🥁','drum','music'],
      ['🪘','long drum','music'],
      ['🎷','saxophone','music'],
      ['🎺','trumpet','music'],
      ['🎸','guitar','music'],
      ['🪕','banjo','music'],
      ['🎻','violin','music'],
      ['🎲','game die','dice game'],
      ['♟️','chess pawn','chess game'],
      ['🎯','direct hit','target bullseye'],
      ['🎳','bowling','game'],
      ['🎮','video game','controller game'],
      ['🎰','slot machine','casino game'],
      ['🧩','puzzle piece','jigsaw'],
    ],
    travel: [
      ['🚗','car','automobile'],
      ['🚕','taxi','car'],
      ['🚙','sport utility vehicle','car suv'],
      ['🚌','bus','transport'],
      ['🚎','trolleybus','transport'],
      ['🏎️','racing car','car'],
      ['🚓','police car','transport'],
      ['🚑','ambulance','transport medical'],
      ['🚒','fire engine','transport'],
      ['🚐','minibus','transport'],
      ['🛻','pickup truck','transport'],
      ['🚚','delivery truck','transport'],
      ['🚛','articulated lorry','truck transport'],
      ['🚜','tractor','farm transport'],
      ['🦯','white cane','accessibility'],
      ['🦽','manual wheelchair','accessibility'],
      ['🦼','motorized wheelchair','accessibility'],
      ['🛴','kick scooter','transport'],
      ['🚲','bicycle','bike transport'],
      ['🛵','motor scooter','transport'],
      ['🏍️','motorcycle','transport'],
      ['🛺','auto rickshaw','transport'],
      ['🚨','police car light','emergency'],
      ['🚔','oncoming police car','transport'],
      ['🚍','oncoming bus','transport'],
      ['🚘','oncoming automobile','transport'],
      ['🚖','oncoming taxi','transport'],
      ['🚡','aerial tramway','transport'],
      ['🚠','mountain cableway','transport'],
      ['🚟','suspension railway','transport'],
      ['🚃','railway car','transport'],
      ['🚋','tram car','transport'],
      ['🚞','mountain railway','transport'],
      ['🚝','monorail','transport'],
      ['🚄','high-speed train','transport'],
      ['🚅','bullet train','transport'],
      ['🚈','light rail','transport'],
      ['🚂','locomotive','train transport'],
      ['🚆','train','transport'],
      ['🚇','metro','subway transport'],
      ['🚊','tram','transport'],
      ['🚉','station','transport'],
      ['✈️','airplane','flight travel'],
      ['🛫','airplane departure','travel'],
      ['🛬','airplane arrival','travel'],
      ['🛩️','small airplane','travel'],
      ['💺','seat','airplane'],
      ['🛰️','satellite','space'],
      ['🚀','rocket','space launch'],
      ['🛸','flying saucer','ufo space'],
      ['🚁','helicopter','transport'],
      ['🛶','canoe','boat'],
      ['⛵','sailboat','boat travel'],
      ['🚤','speedboat','boat'],
      ['🛥️','motor boat','boat'],
      ['🛳️','passenger ship','boat cruise'],
      ['⛴️','ferry','boat'],
      ['🚢','ship','boat cruise'],
      ['⚓','anchor','boat'],
      ['⛽','fuel pump','gas station'],
      ['🚧','construction','barrier'],
      ['🚦','vertical traffic light','signal'],
      ['🚥','horizontal traffic light','signal'],
      ['🗺️','world map','map travel'],
      ['🗿','moai','statue easter island'],
      ['🗽','statue of liberty','nyc usa'],
      ['🗼','tokyo tower','japan'],
      ['🏰','castle','fairytale'],
      ['🏯','japanese castle','japan'],
      ['🏟️','stadium','sport'],
      ['🎡','ferris wheel','amusement'],
      ['🎢','roller coaster','amusement'],
      ['🎠','carousel horse','amusement'],
      ['⛲','fountain','water'],
      ['⛱️','umbrella on ground','beach'],
      ['🏖️','beach with umbrella','vacation'],
      ['🏝️','desert island','vacation'],
      ['🏜️','desert','dry'],
      ['🌋','volcano','mountain'],
      ['⛰️','mountain','nature'],
      ['🏔️','snow-capped mountain','nature'],
      ['🗻','mount fuji','japan'],
      ['🏕️','camping','tent outdoors'],
      ['⛺','tent','camping'],
      ['🏠','house','home'],
      ['🏡','house with garden','home'],
      ['🏘️','houses','neighborhood'],
      ['🏚️','derelict house','abandoned'],
      ['🏗️','building construction','crane'],
      ['🏭','factory','industry'],
      ['🏢','office building','work'],
      ['🏬','department store','shopping'],
      ['🏣','japanese post office','mail'],
      ['🏤','post office','mail'],
      ['🏥','hospital','medical'],
      ['🏦','bank','money'],
      ['🏨','hotel','travel'],
      ['🏪','convenience store','shop'],
      ['🏫','school','education'],
      ['🏩','love hotel','romance'],
      ['💒','wedding','marriage'],
      ['🏛️','classical building','architecture'],
      ['⛪','church','religion'],
      ['🕌','mosque','religion islam'],
      ['🕍','synagogue','religion judaism'],
      ['🛕','hindu temple','religion'],
      ['🕋','kaaba','religion mecca'],
      ['⛩️','shinto shrine','japan'],
      ['🛤️','railway track','train'],
      ['🛣️','motorway','road'],
      ['🗾','map of japan','country'],
      ['🎑','moon viewing ceremony','japan'],
      ['🏞️','national park','nature'],
      ['🌅','sunrise','morning'],
      ['🌄','sunrise over mountains','morning'],
      ['🌠','shooting star','star night'],
      ['🎇','sparkler','fireworks'],
      ['🎆','fireworks','celebration'],
      ['🌇','sunset','evening'],
      ['🌆','cityscape at dusk','evening'],
      ['🏙️','cityscape','city'],
      ['🌃','night with stars','night'],
      ['🌌','milky way','space'],
      ['🌉','bridge at night','golden gate'],
      ['🌁','foggy','weather'],
    ],
    objects: [
      ['⌚','watch','time'],
      ['📱','mobile phone','smartphone'],
      ['📲','mobile phone with arrow','phone'],
      ['💻','laptop','computer'],
      ['⌨️','keyboard','computer'],
      ['🖥️','desktop computer','pc'],
      ['🖨️','printer','office'],
      ['🖱️','computer mouse','pc'],
      ['🖲️','trackball','pc'],
      ['🕹️','joystick','game'],
      ['🗜️','clamp','tool'],
      ['💽','computer disk','data'],
      ['💾','floppy disk','save'],
      ['💿','optical disk','cd'],
      ['📀','dvd','disc'],
      ['📼','videocassette','vhs'],
      ['📷','camera','photo'],
      ['📸','camera with flash','photo'],
      ['📹','video camera','film'],
      ['🎥','movie camera','film'],
      ['📽️','film projector','movie'],
      ['🎞️','film frames','film'],
      ['📞','telephone receiver','phone'],
      ['☎️','telephone','phone'],
      ['📟','pager','old'],
      ['📠','fax machine','office'],
      ['📺','television','tv'],
      ['📻','radio','music'],
      ['🎙️','studio microphone','podcast'],
      ['🎚️','level slider','controls'],
      ['🎛️','control knobs','controls'],
      ['🧭','compass','direction'],
      ['⏱️','stopwatch','time'],
      ['⏲️','timer clock','time'],
      ['⏰','alarm clock','wake up'],
      ['🕰️','mantelpiece clock','time'],
      ['⌛','hourglass done','time'],
      ['⏳','hourglass not done','time'],
      ['📡','satellite antenna','signal'],
      ['🔋','battery','power'],
      ['🔌','electric plug','power'],
      ['💡','light bulb','idea'],
      ['🔦','flashlight','light'],
      ['🕯️','candle','light'],
      ['🪔','diya lamp','light'],
      ['🧯','fire extinguisher','safety'],
      ['🛢️','oil drum','oil'],
      ['💸','money with wings','spending'],
      ['💵','dollar banknote','money usd'],
      ['💴','yen banknote','money jpy'],
      ['💶','euro banknote','money eur'],
      ['💷','pound banknote','money gbp'],
      ['💰','money bag','rich'],
      ['💳','credit card','payment'],
      ['🪙','coin','money'],
      ['⚖️','balance scale','law justice'],
      ['🧰','toolbox','tools'],
      ['🔧','wrench','tool fix'],
      ['🔨','hammer','tool'],
      ['⚒️','hammer and pick','tools'],
      ['🛠️','hammer and wrench','tools'],
      ['⛏️','pick','tool'],
      ['🔩','nut and bolt','hardware'],
      ['⚙️','gear','settings'],
      ['🧱','brick','construction'],
      ['⛓️','chains','link'],
      ['🧲','magnet','attract'],
      ['🔫','water pistol','gun'],
      ['💣','bomb','explosive'],
      ['🧨','firecracker','boom'],
      ['🪓','axe','tool'],
      ['🔪','kitchen knife','blade'],
      ['🗡️','dagger','blade'],
      ['⚔️','crossed swords','fight'],
      ['🛡️','shield','defend'],
      ['🚬','cigarette','smoking'],
      ['⚰️','coffin','death funeral'],
      ['🪦','headstone','grave'],
      ['⚱️','funeral urn','ashes'],
      ['🏺','amphora','greek pottery'],
      ['🔮','crystal ball','fortune'],
      ['📿','prayer beads','religion'],
      ['🧿','nazar amulet','evil eye'],
      ['💈','barber pole','barber'],
      ['⚗️','alembic','science chemistry'],
      ['🔭','telescope','space'],
      ['🔬','microscope','science'],
      ['🕳️','hole','dark'],
      ['💊','pill','medicine'],
      ['💉','syringe','vaccine'],
      ['🩸','drop of blood','blood'],
      ['🩹','adhesive bandage','medical'],
      ['🩺','stethoscope','medical'],
      ['🚪','door','open'],
      ['🛗','elevator','transport'],
      ['🪞','mirror','reflection'],
      ['🪟','window','view'],
      ['🛏️','bed','sleep'],
      ['🛋️','couch and lamp','furniture'],
      ['🪑','chair','furniture'],
      ['🚽','toilet','bathroom'],
      ['🪠','plunger','bathroom'],
      ['🚿','shower','bathroom'],
      ['🛁','bathtub','bathroom'],
      ['🪤','mouse trap','catch'],
      ['🪒','razor','shave'],
      ['🧴','lotion bottle','cosmetics'],
      ['🧷','safety pin','baby'],
      ['🧹','broom','clean'],
      ['🧺','basket','laundry'],
      ['🧻','roll of paper','toilet paper'],
      ['🪣','bucket','clean'],
      ['🧼','soap','clean'],
      ['🪥','toothbrush','dental'],
      ['🧽','sponge','clean'],
      ['🧫','petri dish','science'],
      ['🧬','dna','science genetics'],
      ['🧪','test tube','science'],
      ['🌡️','thermometer','temperature'],
      ['🧹','broom','clean'],
      ['🪅','piñata','party'],
      ['🪆','nesting dolls','russian'],
      ['🎀','ribbon','bow gift'],
      ['🎁','wrapped gift','present'],
      ['📯','postal horn','mail'],
      ['📥','inbox tray','mail'],
      ['📤','outbox tray','mail'],
      ['📦','package','box'],
      ['🏷️','label','tag'],
      ['📪','closed mailbox with lowered flag','mail'],
      ['📫','closed mailbox with raised flag','mail'],
      ['📬','open mailbox with raised flag','mail'],
      ['📭','open mailbox with lowered flag','mail'],
      ['📮','postbox','mail'],
      ['📜','scroll','document'],
      ['📃','page with curl','document'],
      ['📑','bookmark tabs','document'],
      ['📊','bar chart','graph'],
      ['📈','chart increasing','graph up'],
      ['📉','chart decreasing','graph down'],
      ['📄','page facing up','document'],
      ['📅','calendar','date'],
      ['📆','tear-off calendar','date'],
      ['🗓️','spiral calendar','date'],
      ['📇','card index','contact'],
      ['🗃️','card file box','organize'],
      ['🗳️','ballot box with ballot','vote'],
      ['🗄️','file cabinet','organize'],
      ['📋','clipboard','task'],
      ['📁','file folder','folder'],
      ['📂','open file folder','folder'],
      ['🗂️','card index dividers','organize'],
      ['🗞️','rolled-up newspaper','news'],
      ['📰','newspaper','news'],
      ['📓','notebook','journal'],
      ['📔','notebook with decorative cover','journal'],
      ['📒','ledger','accounting'],
      ['📕','closed book','book'],
      ['📗','green book','book'],
      ['📘','blue book','book'],
      ['📙','orange book','book'],
      ['📚','books','library'],
      ['📖','open book','read'],
      ['🔖','bookmark','save'],
      ['🧷','safety pin','clip'],
      ['🔗','link','url chain'],
      ['📎','paperclip','attach'],
      ['🖇️','linked paperclips','attach'],
      ['📐','triangular ruler','geometry'],
      ['📏','straight ruler','measure'],
      ['🧮','abacus','math'],
      ['📌','pushpin','pin'],
      ['📍','round pushpin','location'],
      ['✂️','scissors','cut'],
      ['🖊️','pen','write'],
      ['🖋️','fountain pen','write'],
      ['✒️','black nib','write'],
      ['🖌️','paintbrush','art'],
      ['🖍️','crayon','art'],
      ['📝','memo','note pencil'],
      ['✏️','pencil','write'],
      ['🔍','magnifying glass tilted left','search'],
      ['🔎','magnifying glass tilted right','search'],
      ['🔏','locked with pen','secure'],
      ['🔐','locked with key','secure'],
      ['🔒','locked','lock'],
      ['🔓','unlocked','unlock'],
    ],
    symbols: [
      ['❤️','red heart','love'],
      ['🧡','orange heart','love'],
      ['💛','yellow heart','love'],
      ['💚','green heart','love'],
      ['💙','blue heart','love'],
      ['💜','purple heart','love'],
      ['🖤','black heart','love'],
      ['🤍','white heart','love'],
      ['🤎','brown heart','love'],
      ['❣️','heart exclamation','love'],
      ['💔','broken heart','sad'],
      ['❤️‍🔥','heart on fire','passion'],
      ['❤️‍🩹','mending heart','heal'],
      ['💕','two hearts','love'],
      ['💞','revolving hearts','love'],
      ['💓','beating heart','love'],
      ['💗','growing heart','love'],
      ['💖','sparkling heart','love'],
      ['💘','heart with arrow','cupid'],
      ['💝','heart with ribbon','gift'],
      ['💟','heart decoration','love'],
      ['☮️','peace symbol','peace'],
      ['✝️','latin cross','christian'],
      ['☪️','star and crescent','islam'],
      ['🕉️','om','hindu'],
      ['☸️','wheel of dharma','buddhism'],
      ['✡️','star of david','judaism'],
      ['🔯','dotted six-pointed star','star'],
      ['🕎','menorah','judaism'],
      ['☯️','yin yang','balance'],
      ['☦️','orthodox cross','christian'],
      ['🛐','place of worship','religion'],
      ['⛎','ophiuchus','zodiac'],
      ['♈','aries','zodiac'],
      ['♉','taurus','zodiac'],
      ['♊','gemini','zodiac'],
      ['♋','cancer','zodiac'],
      ['♌','leo','zodiac'],
      ['♍','virgo','zodiac'],
      ['♎','libra','zodiac'],
      ['♏','scorpio','zodiac'],
      ['♐','sagittarius','zodiac'],
      ['♑','capricorn','zodiac'],
      ['♒','aquarius','zodiac'],
      ['♓','pisces','zodiac'],
      ['🆔','ID button','identity'],
      ['⚛️','atom symbol','science'],
      ['🉑','japanese acceptable button','accept'],
      ['☢️','radioactive','danger'],
      ['☣️','biohazard','danger'],
      ['📴','mobile phone off','silent'],
      ['📳','vibration mode','phone'],
      ['🈶','japanese not free of charge button','paid'],
      ['🈚','japanese free of charge button','free'],
      ['🈸','japanese application button','apply'],
      ['🈺','japanese open for business button','open'],
      ['🈷️','japanese monthly amount button','monthly'],
      ['✴️','eight-pointed star','star'],
      ['🆚','VS button','versus'],
      ['💮','white flower','japan'],
      ['🉐','japanese bargain button','bargain'],
      ['㊙️','japanese secret button','secret'],
      ['㊗️','japanese congratulations button','congrats'],
      ['🈴','japanese passing grade button','pass'],
      ['🈵','japanese no vacancy button','full'],
      ['🈹','japanese discount button','discount'],
      ['🈲','japanese prohibited button','forbidden'],
      ['🅰️','A button (blood type)','letter A'],
      ['🅱️','B button (blood type)','letter B'],
      ['🆎','AB button (blood type)','blood'],
      ['🆑','CL button','clear'],
      ['🅾️','O button (blood type)','letter O'],
      ['🆘','SOS button','help'],
      ['❌','cross mark','no wrong'],
      ['⭕','hollow red circle','correct big'],
      ['🛑','stop sign','stop'],
      ['⛔','no entry','stop'],
      ['📛','name badge','tag'],
      ['🚫','prohibited','no'],
      ['💯','hundred points','100 perfect'],
      ['💢','anger symbol','mad'],
      ['♨️','hot springs','onsen'],
      ['🚷','no pedestrians','sign'],
      ['🚯','no littering','sign'],
      ['🚳','no bicycles','sign'],
      ['🚱','non-potable water','sign'],
      ['🔞','no one under eighteen','adult'],
      ['📵','no mobile phones','silent'],
      ['🚭','no smoking','sign'],
      ['❗','red exclamation mark','warning'],
      ['❕','white exclamation mark','warning'],
      ['❓','red question mark','question'],
      ['❔','white question mark','question'],
      ['‼️','double exclamation mark','warning'],
      ['⁉️','exclamation question mark','warning'],
      ['🔅','dim button','dark'],
      ['🔆','bright button','bright'],
      ['〽️','part alternation mark','japan'],
      ['⚠️','warning','caution'],
      ['🚸','children crossing','sign'],
      ['🔱','trident emblem','symbol'],
      ['⚜️','fleur-de-lis','symbol'],
      ['🔰','japanese symbol for beginner','new'],
      ['♻️','recycling symbol','recycle'],
      ['✅','check mark button','yes correct'],
      ['🈯','japanese reserved button','reserved'],
      ['💹','chart increasing with yen','money'],
      ['❇️','sparkle','shine'],
      ['✳️','eight-spoked asterisk','star'],
      ['❎','cross mark button','no'],
      ['🌐','globe with meridians','internet world'],
      ['💠','diamond with a dot','sparkle'],
      ['Ⓜ️','circled M','letter'],
      ['🌀','cyclone','spiral'],
      ['💤','zzz','sleep'],
      ['🏧','ATM sign','money'],
      ['🚾','water closet','restroom'],
      ['♿','wheelchair symbol','accessibility'],
      ['🅿️','P button','parking'],
      ['🛗','elevator','transport'],
      ['🈳','japanese vacancy button','available'],
      ['🈂️','japanese service charge button','service'],
      ['🛂','passport control','customs'],
      ['🛃','customs','border'],
      ['🛄','baggage claim','airport'],
      ['🛅','left luggage','baggage'],
      ['🚹',"men's room",'toilet'],
      ['🚺',"women's room",'toilet'],
      ['🚼','baby symbol','infant'],
      ['🚻','restroom','toilet'],
      ['🚮','litter in bin sign','trash'],
      ['🎦','cinema','movie'],
      ['📶','antenna bars','signal'],
      ['🈁','japanese here button','here'],
      ['🆖','NG button','no good'],
      ['🆗','OK button','okay'],
      ['🆙','UP! button','up'],
      ['🆒','COOL button','cool'],
      ['🆓','FREE button','free'],
      ['0️⃣','keycap: 0','number'],
      ['1️⃣','keycap: 1','number'],
      ['2️⃣','keycap: 2','number'],
      ['3️⃣','keycap: 3','number'],
      ['4️⃣','keycap: 4','number'],
      ['5️⃣','keycap: 5','number'],
      ['6️⃣','keycap: 6','number'],
      ['7️⃣','keycap: 7','number'],
      ['8️⃣','keycap: 8','number'],
      ['9️⃣','keycap: 9','number'],
      ['🔟','keycap: 10','number'],
      ['🔢','input numbers','digits'],
      ['#️⃣','keycap: #','hash'],
      ['*️⃣','keycap: *','star'],
      ['⏏️','eject button','media'],
      ['▶️','play button','media'],
      ['⏸️','pause button','media'],
      ['⏯️','play or pause button','media'],
      ['⏹️','stop button','media'],
      ['⏺️','record button','media'],
      ['⏭️','next track button','media'],
      ['⏮️','last track button','media'],
      ['⏩','fast-forward button','media'],
      ['⏪','fast reverse button','media'],
      ['⏫','fast up button','arrow'],
      ['⏬','fast down button','arrow'],
      ['◀️','reverse button','media'],
      ['🔼','upwards button','arrow'],
      ['🔽','downwards button','arrow'],
      ['➡️','right arrow','arrow'],
      ['⬅️','left arrow','arrow'],
      ['⬆️','up arrow','arrow'],
      ['⬇️','down arrow','arrow'],
      ['↗️','up-right arrow','arrow'],
      ['↘️','down-right arrow','arrow'],
      ['↙️','down-left arrow','arrow'],
      ['↖️','up-left arrow','arrow'],
      ['↕️','up-down arrow','arrow'],
      ['↔️','left-right arrow','arrow'],
      ['↪️','left arrow curving right','arrow'],
      ['↩️','right arrow curving left','arrow'],
      ['⤴️','right arrow curving up','arrow'],
      ['⤵️','right arrow curving down','arrow'],
      ['🔀','shuffle tracks button','random'],
      ['🔁','repeat button','loop'],
      ['🔂','repeat single button','loop'],
      ['🔄','counterclockwise arrows button','refresh'],
      ['🔃','clockwise vertical arrows','refresh'],
      ['🎵','musical note','music'],
      ['🎶','musical notes','music'],
      ['➕','plus','math add'],
      ['➖','minus','math subtract'],
      ['➗','divide','math'],
      ['✖️','multiply','math'],
      ['🟰','heavy equals sign','math'],
      ['♾️','infinity','forever'],
      ['💲','heavy dollar sign','money'],
      ['💱','currency exchange','money'],
      ['™️','trade mark','trademark'],
      ['©️','copyright','c'],
      ['®️','registered','r'],
      ['〰️','wavy dash','squiggle'],
      ['➰','curly loop','swirl'],
      ['➿','double curly loop','swirl'],
      ['🔚','END arrow','arrow'],
      ['🔙','BACK arrow','arrow'],
      ['🔛','ON! arrow','arrow'],
      ['🔝','TOP arrow','arrow'],
      ['🔜','SOON arrow','arrow'],
      ['✔️','check mark','yes'],
      ['☑️','check box with check','yes'],
      ['🔘','radio button','select'],
      ['🔴','red circle','circle dot'],
      ['🟠','orange circle','circle'],
      ['🟡','yellow circle','circle'],
      ['🟢','green circle','circle'],
      ['🔵','blue circle','circle'],
      ['🟣','purple circle','circle'],
      ['⚫','black circle','dot'],
      ['⚪','white circle','dot'],
      ['🟤','brown circle','circle'],
      ['🔺','red triangle pointed up','triangle'],
      ['🔻','red triangle pointed down','triangle'],
      ['🔸','small orange diamond','shape'],
      ['🔹','small blue diamond','shape'],
      ['🔶','large orange diamond','shape'],
      ['🔷','large blue diamond','shape'],
      ['🔳','white square button','square'],
      ['🔲','black square button','square'],
      ['▪️','black small square','square'],
      ['▫️','white small square','square'],
      ['◾','black medium-small square','square'],
      ['◽','white medium-small square','square'],
      ['◼️','black medium square','square'],
      ['◻️','white medium square','square'],
      ['🟥','red square','square'],
      ['🟧','orange square','square'],
      ['🟨','yellow square','square'],
      ['🟩','green square','square'],
      ['🟦','blue square','square'],
      ['🟪','purple square','square'],
      ['⬛','black large square','square'],
      ['⬜','white large square','square'],
      ['🟫','brown square','square'],
      ['🔈','speaker low volume','sound'],
      ['🔇','muted speaker','mute'],
      ['🔉','speaker medium volume','sound'],
      ['🔊','speaker high volume','sound'],
      ['🔔','bell','notification'],
      ['🔕','bell with slash','mute'],
      ['📣','megaphone','announce'],
      ['📢','loudspeaker','announce'],
      ['👁️‍🗨️','eye in speech bubble','witness'],
      ['💬','speech balloon','chat'],
      ['💭','thought balloon','thinking'],
      ['🗯️','right anger bubble','annoyed'],
      ['♠️','spade suit','cards'],
      ['♣️','club suit','cards'],
      ['♥️','heart suit','cards'],
      ['♦️','diamond suit','cards'],
      ['🃏','joker','cards'],
      ['🎴','flower playing cards','japan'],
      ['🀄','mahjong red dragon','game'],
      ['🕐',"one o'clock",'time'],
      ['🕑',"two o'clock",'time'],
      ['🕒',"three o'clock",'time'],
      ['🕓',"four o'clock",'time'],
      ['🕔',"five o'clock",'time'],
      ['🕕',"six o'clock",'time'],
      ['🕖',"seven o'clock",'time'],
      ['🕗',"eight o'clock",'time'],
      ['🕘',"nine o'clock",'time'],
      ['🕙',"ten o'clock",'time'],
      ['🕚',"eleven o'clock",'time'],
      ['🕛',"twelve o'clock",'time'],
    ],
    flags: [
      ['🏳️','white flag','flag'],
      ['🏴','black flag','flag'],
      ['🏁','chequered flag','race finish'],
      ['🚩','triangular flag','red flag'],
      ['🏳️‍🌈','rainbow flag','pride lgbt'],
      ['🏴‍☠️','pirate flag','pirate'],
      ['🇺🇸','flag United States','usa'],
      ['🇬🇧','flag United Kingdom','uk britain'],
      ['🇨🇦','flag Canada','canada'],
      ['🇦🇺','flag Australia','australia'],
      ['🇩🇪','flag Germany','germany'],
      ['🇫🇷','flag France','france'],
      ['🇪🇸','flag Spain','spain'],
      ['🇮🇹','flag Italy','italy'],
      ['🇯🇵','flag Japan','japan'],
      ['🇨🇳','flag China','china'],
      ['🇰🇷','flag South Korea','korea'],
      ['🇮🇳','flag India','india'],
      ['🇧🇷','flag Brazil','brazil'],
      ['🇲🇽','flag Mexico','mexico'],
      ['🇷🇺','flag Russia','russia'],
      ['🇿🇦','flag South Africa','south africa'],
      ['🇳🇿','flag New Zealand','new zealand'],
      ['🇮🇪','flag Ireland','ireland'],
      ['🇳🇱','flag Netherlands','netherlands'],
      ['🇸🇪','flag Sweden','sweden'],
      ['🇳🇴','flag Norway','norway'],
      ['🇫🇮','flag Finland','finland'],
      ['🇩🇰','flag Denmark','denmark'],
      ['🇨🇭','flag Switzerland','switzerland'],
      ['🇦🇹','flag Austria','austria'],
      ['🇧🇪','flag Belgium','belgium'],
      ['🇵🇱','flag Poland','poland'],
      ['🇨🇿','flag Czechia','czech'],
      ['🇬🇷','flag Greece','greece'],
      ['🇵🇹','flag Portugal','portugal'],
      ['🇹🇷','flag Turkey','turkey'],
      ['🇸🇦','flag Saudi Arabia','saudi'],
      ['🇦🇪','flag UAE','uae emirates'],
      ['🇮🇱','flag Israel','israel'],
      ['🇪🇬','flag Egypt','egypt'],
      ['🇹🇭','flag Thailand','thailand'],
      ['🇻🇳','flag Vietnam','vietnam'],
      ['🇮🇩','flag Indonesia','indonesia'],
      ['🇸🇬','flag Singapore','singapore'],
      ['🇲🇾','flag Malaysia','malaysia'],
      ['🇵🇭','flag Philippines','philippines'],
      ['🇦🇷','flag Argentina','argentina'],
      ['🇨🇱','flag Chile','chile'],
      ['🇨🇴','flag Colombia','colombia'],
      ['🇵🇪','flag Peru','peru'],
      ['🇻🇪','flag Venezuela','venezuela'],
      ['🇳🇬','flag Nigeria','nigeria'],
      ['🇰🇪','flag Kenya','kenya'],
      ['🇪🇹','flag Ethiopia','ethiopia'],
      ['🇲🇦','flag Morocco','morocco'],
      ['🇺🇦','flag Ukraine','ukraine'],
      ['🇭🇰','flag Hong Kong','hong kong'],
      ['🇹🇼','flag Taiwan','taiwan'],
      ['🇪🇺','flag European Union','eu europe'],
    ],
  },
};
